unit TPBOOK1;

interface

const

  hcH11_1                = 15;
  hcH11_2                = 16;
  hcH11_3                = 17;
  hcH11_4                = 18;
  hcH12_1                = 19;
  hcH12_10               = 26;
  hcH12_11               = 27;
  hcH12_12               = 28;
  hcH12_13               = 29;
  hcH12_14               = 30;
  hcH12_16               = 31;
  hcH12_17               = 32;
  hcH12_18               = 33;
  hcH12_19               = 34;
  hcH12_2                = 20;
  hcH12_20               = 35;
  hcH12_21               = 36;
  hcH12_22               = 37;
  hcH12_23               = 38;
  hcH12_24               = 39;
  hcH12_25               = 40;
  hcH12_26               = 41;
  hcH12_27               = 42;
  hcH12_28               = 43;
  hcH12_30               = 44;
  hcH12_31               = 45;
  hcH12_32               = 46;
  hcH12_33               = 47;
  hcH12_34               = 48;
  hcH12_35               = 49;
  hcH12_36               = 50;
  hcH12_38               = 51;
  hcH12_39               = 52;
  hcH12_4                = 21;
  hcH12_40               = 53;
  hcH12_41               = 54;
  hcH12_42               = 55;
  hcH12_44               = 56;
  hcH12_45               = 57;
  hcH12_46               = 58;
  hcH12_47               = 59;
  hcH12_48               = 60;
  hcH12_49               = 61;
  hcH12_5                = 22;
  hcH12_50               = 62;
  hcH12_52               = 63;
  hcH12_53               = 64;
  hcH12_54               = 65;
  hcH12_56               = 66;
  hcH12_57               = 67;
  hcH12_58               = 68;
  hcH12_59               = 69;
  hcH12_60               = 70;
  hcH12_61               = 71;
  hcH12_62               = 72;
  hcH12_63               = 73;
  hcH12_64               = 74;
  hcH12_65               = 75;
  hcH12_66               = 76;
  hcH12_67               = 77;
  hcH12_68               = 78;
  hcH12_69               = 79;
  hcH12_7                = 23;
  hcH12_70               = 80;
  hcH12_71               = 81;
  hcH12_72               = 82;
  hcH12_73               = 83;
  hcH12_8                = 24;
  hcH12_9                = 25;
  hcHead11               = 4;
  hcHead12               = 5;
  hcHead12_2             = 6;
  hcHead13               = 7;
  hcHead13_1             = 8;
  hcHead13_2             = 9;
  hcHead13_3             = 10;
  hcHead14               = 11;
  hcHead14_1             = 12;
  hcHead14_2             = 13;
  hcHead14_3             = 14;
  hcNoContext            = 3;

implementation

end.
